{{- if .Values.api.enabled }}
{{- $root := . -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: governor-api-config
  annotations:
    argocd.argoproj.io/sync-wave: '-1'
  labels:
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    {{- with .Values.api.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
data:
  .governor.yaml: |
    admin-groups:
      - {{ .Values.api.adminGroups }}

    nats:
      url: {{ .Values.api.nats.url }}
      creds-file: {{ .Values.api.nats.credsPath }}/governor-api-nats-client-creds
      subject-prefix: {{ .Values.api.nats.subjectPrefix }}
      use-runtime-access-token: {{ .Values.api.nats.useRuntimeAccessToken }}

    iam-runtime:
      socket: {{ .Values.api.iamRuntime.socket }}
      timeout: {{ .Values.api.iamRuntime.timeout }}

    oidc:
    {{- range .Values.api.oidc }}
      - issuer:  {{ .issuer }}
        audience: {{ .audience }}
        jwksuri: {{ .jwksuri }}
        enabled: {{ .enabled }}
        {{- if or .rolesClaim .userClaim }}
        claims:
        {{- end }}
          {{- if .rolesClaim }}
          roles: {{ .rolesClaim }}
          {{- end }}
          {{- if .userClaim }}
          username: {{ .userClaim }}
          {{- end }}
    {{- end }}

    {{- if .Values.api.debug }}
    logging:
      debug: true
      pretty: true
    {{- end }}

    {{- if .Values.api.tracing.enabled }}
    tracing:
      enabled: true
    {{- end }}

    db:
      connections:
        max_open: {{ .Values.api.db.connections.max_open }}
        max_idle: {{ .Values.api.db.connections.max_idle }}
        max_lifetime: {{ .Values.api.db.connections.max_lifetime }}
{{- end }}
