{{- if .Values.api.enabled }}
---
apiVersion: {{ include "common.capabilities.ingress.apiVersion" . }}
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  name: governor-api
  labels: {{- include "common.labels.standard" . | nindent 4 }}
spec:
  ingressClassName: nginx-governor
  rules:
    - host: {{ .Values.api.ingress.host }}
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: governor-api
                port:
                  name: http
          - path: "/healthz"
            pathType: Prefix
            backend:
              service:
                name: governor-api
                port:
                  name: http
  tls:
    - hosts:
        - {{ .Values.api.ingress.host }}
      secretName: governor-api-tls
{{- end }}
