{{- if .Values.api.enabled }}
{{- if .Values.api.db.secrets.enabled }}
---
kind: Secret
apiVersion: v1
metadata:
  name: db-uri
  labels:
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    {{- with .Values.api.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
type: Opaque
data:
  GOVERNOR_DB_URI: {{ .Values.api.db.secrets.uri }}
---
kind: Secret
apiVersion: v1
metadata:
  name: governor-api-crdb-ca
  labels:
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    {{- with .Values.api.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
type: Opaque
data:
  ca.crt: {{ .Values.api.db.secrets.crdbCrt }}
{{- end }}
{{- if .Values.api.nats.secrets.enabled }}
---
kind: Secret
apiVersion: v1
metadata:
  name: governor-api-nats-creds
  labels:
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    {{- with .Values.api.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
type: Opaque
data:
  governor-nats-client-creds: {{ .Values.api.nats.secrets.clientCreds }}
{{- end }}
{{- if .Values.api.tracing.secrets.enabled }}
---
kind: Secret
apiVersion: v1
metadata:
  name: honeycomb-key
  labels:
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    {{- with .Values.api.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
type: Opaque
data:
  honeycomb-key: {{ .Values.api.tracing.secrets.honeycombKey }}
{{- end }}
{{- end }}
