{{- if .Values.api.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: governor-api
  labels: 
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    {{- with .Values.api.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 3001
  selector: 
  {{- with .Values.api.matchLabels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  sessionAffinity: None
  type: ClusterIP
{{- end }}
