{{- if .Values.oktaAddon.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: gov-okta-addon
  labels: 
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    {{- with .Values.oktaAddon.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: {{ .Values.oktaAddon.port }}
  selector: 
  {{- with .Values.oktaAddon.matchLabels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  sessionAffinity: None
  type: ClusterIP
 {{- end }}