{{- if .Values.slackAddon.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: gov-slack-addon
  labels: 
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    {{- with .Values.slackAddon.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.slackAddon.service.type }}
  ports:
    - port: {{ .Values.slackAddon.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector: 
  {{- with .Values.slackAddon.matchLabels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
