{{- if .Values.slackAddon.enabled }}
apiVersion: {{ include "common.capabilities.deployment.apiVersion" . }}
kind: Deployment
metadata:
  name: gov-slack-addon
  labels: 
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    {{- with .Values.slackAddon.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if not .Values.slackAddon.autoscaling.enabled }}
  replicas: {{ .Values.slackAddon.replicas }}
  {{- end }}
  revisionHistoryLimit: 3
  selector:
    matchLabels: 
    {{- with .Values.slackAddon.matchLabels }}
      {{- toYaml . | nindent 6 }}
    {{- end }}
  template:
    metadata:
      labels: 
        helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
        {{- with .Values.slackAddon.labels }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/slack-addon-configmap.yaml") . | sha256sum }}
    spec:
    {{- with .Values.slackAddon.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- if .Values.audit.enabled }}
      initContainers:
      # Optional: Pre-creates the `/app-audit/audit.log` named pipe.
      - image: "{{ .Values.audit.auditImage.repository }}:{{ .Values.audit.auditImage.tag | default .Chart.AppVersion }}"
        {{- with .Values.audit.securityContext }}
        securityContext:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        args:
          - 'init'
          - '-f'
          - '/app-audit/audit.log'
        name: init-audit-logs
        imagePullPolicy: Always
        volumeMounts:
          - mountPath: /app-audit
            name: audit-logs
      {{- with .Values.audit.initContainer.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
      {{- end }}
    {{- end }}
      containers:
        - name: gov-slack-addon
          args:
            - serve
          envFrom:
          - configMapRef:
              name: gov-slack-addon-config
          - secretRef:
              name: gov-slack-addon-creds
          {{- with .Values.slackAddon.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.slackAddon.image.repository }}:{{ .Values.slackAddon.image.tag | default .Chart.AppVersion }}"
          {{- with .Values.slackAddon.image.pullPolicy }}
          imagePullPolicy: {{ . }}
          {{- end }}
          {{- with .Values.slackAddon.ports }}
          ports:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          livenessProbe:
            httpGet:
              path: /healthz/liveness
              port: http
          readinessProbe:
            httpGet:
              path: /healthz/readiness
              port: http
          {{- with .Values.slackAddon.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
          - name: natscreds
            mountPath: "/nats"
            readOnly: true
        {{- if .Values.audit.enabled }} # Begin audittail toggle
          # This is mounted in the 1st container
          - name: audit-logs
            mountPath: /app-audit
        # This is the audit container
        - name: gov-slack-addon-audit
          {{- with .Values.audit.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          args:
            - -f
            - /app-audit/audit.log
          image: "{{ .Values.audit.auditImage.repository }}:{{ .Values.audit.auditImage.tag | default .Chart.AppVersion }}"
          volumeMounts:
          - name: audit-logs
            mountPath: /app-audit
          {{- with .Values.audit.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
        {{- end }} # End audittail toggle
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      volumes:
      - name: natscreds
        secret:
          secretName: gov-slack-addon-nats-creds
          defaultMode: 0444
      {{- if .Values.audit.enabled }}
      - name: audit-logs
        emptyDir: {}
      {{- end }}
      {{- with .Values.slackAddon.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.slackAddon.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
