apiVersion: v2
name: governor
description: A helm chart for the Governor ecosystem
type: application
version: 0.2.0
appVersion: v0.0.1

dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 2.27.0
