# -- governor-api settings
api:
  # -- enable the governor-api components
  enabled: true

  # -- set of additional labels for the application 
  labels:
    app.kubernetes.io/instance: governor
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: governor
    app.kubernetes.io/component: api

  # -- set of additional match labels for the application 
  matchLabels:
    app.kubernetes.io/instance: governor
    app.kubernetes.io/name: governor

  # -- set to true to turn on debug logging
  debug: false

  # -- image for the governor-api
  image:
    # -- container image repository for the governor-api image
    repository: ghcr.io/metal-toolbox/governor-api
    # -- image tag version
    tag: v0.3.0
    # -- image pull policy for the governor-api container
    pullPolicy: IfNotPresent

  # -- ingress settings for the governor-api
  ingress:
    # -- host definition for the api ingress
    host: api.governor.example.com
    # -- prefix use for the governor api ingress
    prefix: api.governor

  # -- readiness probe definitions for the governor-api pod
  readinessProbe:
    # -- interval to run the readiness probe
    periodSeconds: 20
    # -- number of seconds to wait for the probe to timeout
    timeoutSeconds: 3
    # -- minimum consecutive successes for probe to be considered successful
    successThreshold: 1
    # -- minimum consecutive failures for the probe to be considered unhealthy
    failureThreshold: 3

  # -- admin group for highest level permissions in the governor-api
  adminGroups: "governor-admins"

  # -- nats settings for the governor-api
  nats:
    # -- url to connection to nats
    url:
    # -- mount path for the nats creds file
    credsPath: /nats
    # -- subject prefix used for the nats events
    subjectPrefix: governor.events
    # -- nats secrets definitions
    secrets:
      # -- enable helm secrets, set to `true` if you want to set the value directly in the chart (not recommended)
      enabled: false
      # -- client credentials secrets
      clientCreds:

  # --  oidc settings, currently startup will fail without a valid oidc config
  oidc:
    # -- a unique identifier for your app that is issued to you when you register your app with the IdP
    - audience: ""
      issuer: ""
      jwksuri: ""
      enabled: true
      rolesClaim: ""
      userClaim: ""

  # -- replicas of the governor-api
  replicaCount: 2
  # -- resource settings for the governor-api
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 128Mi

  # -- settings for the backend db
  db:
    connections:
      max_open: 20
      max_idle: 20
      max_lifetime: 0
    # -- db secrets, set to `true` if you want to set the value directly in the chart (not recommended)
    secrets:
      enabled: false
      uri:
      crdbCrt:
    uri:
      existingSecret: db-uri
  # -- tracing settings
  tracing:
    enabled: true
    # -- tracing secrets, set to `true` if you want to set the value directly in the chart (not recommended)
    secrets:
      enabled: false
      honeycombKey:

# -- slack-addon settings
slackAddon:
  # -- set to false to disable this addon completely
  enabled: true

  # -- ports for the slack addon container
  ports:
    - name: http
      containerPort: 8000

  # -- set of labels for the application 
  labels:
    app.kubernetes.io/instance: gov-slack-addon
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: gov-slack-addon

  # -- set of match labels for the application 
  matchLabels:
    app.kubernetes.io/instance: gov-slack-addon
    app.kubernetes.io/name: gov-slack-addon

  # -- set to true to turn on debug logging
  debug: false
  # -- set to true for human readable logging
  pretty: false
  # -- dryrun on the reconcile loop
  dryrun: false

  # -- governor-api settings to retrieve required information by the slack addon
  api:
    url: https://api.governor.example.com
    clientId: gov-slack-addon-governor
    audience: https://api.governor.example.com

  # -- hydra settings for communication with the governor-api
  hydra:
    url: https://hydra.example.com/oauth2/token


  # -- nats setup for the slack addon
  nats:
    url: tls://nats.governor.example.com:4222,
    credsPath: /nats
    subjectPrefix: governor.events

  # reconciler will run at the defined interval to ensure no events were missed
  reconciler:
    interval: 1h
    locking: true

  replicas: 1

  autoscaling:
    enabled: false

  nodeSelector:

  tolerations:

  # -- image settings for the slack addon
  image:
    repository: ghcr.io/metal-toolbox/governor-slack-addon
    tag: "46-c41b0158"
    pullPolicy: IfNotPresent

  # -- Security context to be added to the deployment
  securityContext:
    capabilities:
      drop:
        - ALL
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    runAsUser: 1000

  service:
    port: 80

  # -- (dict) resource limits & requests
  # ref: https://kubernetes.io/docs/user-guide/compute-resources/
  resources:
    limits:
      cpu: 500m
      memory: 500Mi
    requests:
      cpu: 250m
      memory: 500Mi

# -- audit sidecar settings
audit:
  enabled: true
  auditImage:
    repository: ghcr.io/metal-toolbox/audittail
    tag: v0.8.0
    pullPolicy: IfNotPresent
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 128Mi
  initContainer:
    resources:
      limits:
        cpu: 100m
        memory: 20Mi
      requests:
        cpu: 100m
        memory: 20Mi
  securityContext:
    capabilities:
      drop:
        - ALL
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    runAsUser: 1000
